- .travis.yml
- README.md
- test/routes/mock-view-engine.js
- test/routes/test-route-index.js
- test/routes/test-route-status.js
Updated .travis.yml to remove redundant lines and updated README with badge
> apvs-340 - updated for travis integration

- test/routes/test-route-index.js
> apvs-340 - fixed tests in travis

- .gitignore
- Dockerfile
- Dockerfile-dev
- README.md
- app/bin/www
- docker-compose.yml
- gulpfile.js
- package.json
- test/e2e/spec.js
- test/unit/routes/mock-view-engine.js
- test/unit/routes/test-route-index.js
- test/unit/routes/test-route-status.js
- wdio.conf.js
Added simple e2e selenium test for hitting landing page
> Feature/apvs 340/add e2e tests

- README.md
- gulpfile.js
- package.json
- test/wdio.conf.js
- test/wdio.conf.sauce.firefox.js
- test/wdio.conf.sauce.ie8.js
> apvs-340 - added saucelabs config for running tests

- Dockerfile-dev
- README.md
- gulpfile-e2e.js
- gulpfile.js
- package.json
chore - moved e2e to separate gulpfile
> chore - moved e2e to separate gulpfile

- README.md
- package.json
chore - added "npm run-script e2e" commands to run e2e tests
> chore - added "npm run-script e2e" commands to run e2e tests

- app/services/validators/eligibility/date-of-birth-validator.js
- test/unit/services/validators/eligibility/test-date-of-birth-validator.js
Added unit tests for `date-of-birth-validator.js`
- Added unit tests for `date-of-birth-validator.js`
- Added TODOs for further work.
> Added unit test for date-of-birth-validator.

- .gitignore
- app/services/validators/eligibility/benefit-validator.js
- app/services/validators/eligibility/date-of-birth-validator.js
- app/services/validators/eligibility/journey-assistance-validator.js
- app/services/validators/eligibility/prisoner-relationship-validator.js
- app/services/validators/field-validator.js
- app/services/validators/fieldset-validator.js
- app/services/validators/validation-error-messages.js
- app/services/validators/validation-field-names.js
- test/unit/routes/eligibility/test-first-time-eligibility-flow.js
- test/unit/routes/health-check/test-status.js
- test/unit/routes/test-index.js
- test/unit/services/test-date-formatter.js
- test/unit/services/test-reference-generator.js
- test/unit/services/test-service-log.js
- test/unit/services/validators/eligibility/test-benefit-validator.js
- test/unit/services/validators/eligibility/test-date-of-birth-validator.js
- test/unit/services/validators/eligibility/test-journey-assistance-validator.js
- test/unit/services/validators/eligibility/test-prisoner-relationship-validator.js
- test/unit/services/validators/test-error-handler.js
- test/unit/services/validators/test-field-validator.js
- test/unit/services/validators/test-fieldset-validator.js
Refactored the FieldValidation class to use the ErrorHandler class. Added missing unit tests and refactored existing tests.
- Incorporated the ErrorHandler class into the FieldValidator class. 
- Added unit tests for the FieldValidator class.
- Updated each of the classes that where using the FieldValidator.
- Updated the tests for each of the classes, included tests for edge cases.
- Updated all tests to specify the file path to the test.
- Updated .gitignore file to ignore local scripts.
> Incorporated the ErrorHandler class into the FieldValidator class.

- app/routes/application-submitted.js
- app/routes/first-time/about-you.js
- app/services/data/first-time-claim.js
- app/services/data/visitor.js
- app/views/application-submitted.html
- app/views/first-time/about-you.html
- migrations/20161018165723_add-visitor.js
- package.json
- test/integration/services/data/test-first-time-claim.js
- test/integration/services/data/test-visitor.js
- test/unit/routes/first-time/test-about-the-prisoner.js
- test/unit/routes/first-time/test-about-you.js
apvs-341 - added about-you route and persistence logic
> Feature/apvs 341/about you persistence

- app/routes/first-time/about-the-prisoner.js
- app/services/validators/field-validator.js
- app/services/validators/first-time/about-the-prisoner-validator.js
- app/services/validators/validation-error-messages.js
- app/services/validators/validation-field-names.js
- app/views/eligibility/date-of-birth.html
- app/views/first-time/about-the-prisoner.html
- test/unit/routes/first-time/test-about-the-prisoner.js
- test/unit/services/validators/first-time/test-about-the-prisoner-validator.js
- test/unit/services/validators/test-field-validator.js
Added field validation to about-the-prisoner page
List high-level components of the application that this PR will affect.
* added about-the-prisoner-validator
* added the validator to the about-the-prisoner route and html page
> Feature/apvs 341/about the prisoner field validation

- app/services/data/first-time-claim.js
- package.json
- test/integration/services/data/test-first-time-claim.js
List high-level components of the application that this PR will affect.
* A list of
* The changes made
* To this component
* ...
> chore - refactor to use dateformatter

- .github/PULL_REQUEST_TEMPLATE
List high-level components of the application that this PR will affect.
* A list of
* The changes made
* To this component
* ...
> chore - shortened pull template

- app/views/first-time/about-you.html
Bug fix - About you country not remaining on error
* Added nunjucks to check which checkbox should be selected to fix bug
> Bug fix - About you country not remaining on error

- app/routes/first-time/date-of-birth.js
- test/unit/routes/first-time/test-date-of-birth.js
apvs-341 - added redirect to fail if sixteen or under
> apvs-341 - added redirect to fail if sixteen or under

- .github/PULL_REQUEST_TEMPLATE
- .gitignore
- README.md
- package.json
chore - added istanbul for code coverage
> chore - added istanbul for code coverage

- test/unit/routes/first-time/test-about-the-prisoner.js
- test/unit/routes/first-time/test-about-you.js
chore - removed urlvalidator tests covered by urlValidatorCalled
> chore - removed urlvalidator tests covered by urlValidatorCalled

- app/views/application-submitted.html
- app/views/dev/display-data-for-reference.html
- app/views/dev/gov-notify.html
- app/views/eligibility-fail.html
- app/views/eligibility-requirements.html
- app/views/first-time/about-the-prisoner.html
- app/views/first-time/about-you.html
- app/views/first-time/benefits.html
- app/views/first-time/date-of-birth.html
- app/views/first-time/journey-assistance.html
- app/views/first-time/prisoner-relationship.html
- app/views/includes/error.html
- app/views/includes/layout.html
- app/views/includes/validation-error-messages.html
- app/views/index.html
- app/views/payment/bank-account-details.html
- app/views/start.html
- app/views/ux/claim/additional-expenses.html
- app/views/ux/claim/car-details.html
- app/views/ux/claim/claim-details.html
- app/views/ux/claim/claim-summary.html
- app/views/ux/claim/light-refreshment-details.html
- app/views/ux/claim/profile.html
- app/views/ux/claim/taxi-details.html
- app/views/ux/claim/train-details.html
- app/views/ux/claim/transport.html
- app/views/ux/claim/visit-type.html
- app/views/ux/claim/your-journey.html
- app/views/ux/eligibility/confirm-your-details.html
- app/views/ux/file-upload.html
Replaced 4 space indentation with 2 space indentation in all HTML pages.
- Removed completed TODO.
- Fixed some minor HTML issues (unclosed tags, for with incorrect id)
> Replaced 4 space indentation with 2 space indentation in all HTML pages.

- migrations/20161024084858_add-claim.js
- migrations/20161024084907_add-claim-transport.js
- migrations/20161024084915_add-claim-expense.js
- migrations/20161024084923_add-claim-bank-details.js
apvs-346 - add claim migrations
> apvs-346 - add claim migrations

- app/views/includes/error-404.html
> Corrected typo.

- app/views/application-submitted.html
> apvs-357 - add print link

- app/views/application-submitted.html
apvs-357 - add download confirmation of visit form link
> Feature/apvs 357/add download confirmation form link

- migrations/20161024155652_add-additional-claim-transport-columns.js
- migrations/20161024155659_add-additional-claim-expense-columns.js
apvs-346 - added additional columns for expenses
> apvs-346 - added additional columns for expenses

- gulpfile.js
- package.json
chore - separate task to generate assets without starting
> chore - separate task to generate assets without starting

- migrations/20161026085018_add-task.js
apvs-357 - added task table migration
> apvs-357 - added task migration

- app/routes/first-time/eligibility/claim/bank-account-details.js
- app/services/validators/url-path-validator.js
- test/unit/services/validators/test-url-path-validator.js
- Simplified the UrlPathValidator.
- Gave the bank-account-details the same param name for claim as the other pages (the url path validator won't work as expected otherwise).
- Updated unit test.
> Simplified the UrlPathValidator.

- .github/PULL_REQUEST_TEMPLATE
Updated template to include End-to-End test checkbox.
> Updated template to include End-to-End test checkbox.

- app/routes/first-time/eligibility/claim/accommodation-details.js
- app/routes/first-time/eligibility/claim/bank-account-details.js
- app/routes/first-time/eligibility/claim/bus-details.js
- app/routes/first-time/eligibility/claim/car-details.js
- app/routes/first-time/eligibility/claim/car-hire-details.js
- app/routes/first-time/eligibility/claim/expenses.js
- app/routes/first-time/eligibility/claim/ferry-details.js
- app/routes/first-time/eligibility/claim/light-refreshment-details.js
- app/routes/first-time/eligibility/claim/plane-details.js
- app/routes/first-time/eligibility/claim/taxi-details.js
- app/routes/first-time/eligibility/claim/train-details.js
- app/routes/routes.js
- app/routes/ux/claim/claim-details.js
- app/services/routing/expenses-url-router.js
- app/services/validators/url-path-validator.js
- app/views/first-time/eligibility/claim/accommodation-details.html
- app/views/first-time/eligibility/claim/bank-account-details.html
- app/views/first-time/eligibility/claim/bus-details.html
- app/views/first-time/eligibility/claim/car-details.html
- app/views/first-time/eligibility/claim/car-hire-details.html
- app/views/first-time/eligibility/claim/expenses.html
- app/views/first-time/eligibility/claim/ferry-details.html
- app/views/first-time/eligibility/claim/light-refreshment-details.html
- app/views/first-time/eligibility/claim/plane-details.html
- app/views/first-time/eligibility/claim/taxi-details.html
- app/views/first-time/eligibility/claim/train-details.html
- test/unit/services/validators/test-url-path-validator.js
- Updated all instances of :claim to :claimId in the routes.
- Renamed the corresponding parameter in both the routes and the views.
- Updated tests to cope with name change.
- bank-account-details was passing it's reference and claimId params in a non-standard way. Refactored to use our typical format.
> Updated all instances of :claim to :claimId in the routes.

- app/routes/first-time/eligibility/claim/bank-account-details.js
chore - fix bank account details render
We weren't passing the reference and claimId to the html page when there were validation errors
> chore - fix bank account details render

- app/services/data/submit-first-time-claim.js
- migrations/20161028100917_drop-claim-transport-enhance-claim-expense.js
- test/integration/services/data/test-submit-first-time-claim.js
chore - refactor to remove claim transport table
> chore - refactor to remove claim transport table

- app/services/routing/expenses-url-router.js
- app/services/routing/param-builder.js
- test/unit/services/routing/test-expenses-url-router.js
- test/unit/services/routing/test-param-builder.js
- Moved the param building and formatting logic from the expense-url-router into another file.
- Added unit tests for the expense-url-router.
- Added unit tests for the param-builder.
- Removed completed TODOs.
> Feature/apvs 664/completed expense routing including unit tests

- package.json
- test/wdio.conf.sauce.ie8.jenkins.js
> simple change for jenkins

- app/routes/first-time/eligibility/claim/claim-summary.js
- app/services/data/get-individual-claim-details.js
- app/views/first-time/eligibility/claim/claim-summary.html
- app/views/helpers/claim-expense-helper.js
- app/views/helpers/date-helper.js
- app/views/helpers/display-field-names.js
- test/unit/routes/first-time/eligibility/claim/test-claim-summary.js
- test/unit/views/helpers/test-claim-expense-helper.js
- test/unit/views/helpers/test-date-helper.js
apvs-351 - added claim details to summary
> Feature/apvs 351/update claim summary

- migrations/20161031145302_update-eligibility-add-benefit.js
chore - added benefits to eligibility
> chore - added benefits to eligibility

- app/routes/first-time/eligibility/new-claim/journey-information.js
- app/views/first-time/eligibility/new-claim/journey-information.html
chore - remove escort questions
> chore - remove escort questions

- package.json
- test/wdio.conf.sauce.firefox.jenkins.js
> Adding jekins test for firefox

- app/services/data/get-travelling-from-and-to.js
- app/services/validators/validation-error-messages.js
- From is now the town only.
- Updated currency error message.
> Fixed from.

- app/views/includes/layout.html
chore - fix type in cookie info bar
> chore - fix type in cookie info bar

- test/unit/services/domain/expenses/test-accommodation-expense.js
- test/unit/services/domain/expenses/test-bus-expense.js
- test/unit/services/domain/expenses/test-car-expense.js
- test/unit/services/domain/expenses/test-ferry-expense.js
- test/unit/services/domain/expenses/test-hire-expenses.js
- test/unit/services/domain/expenses/test-plane-expense.js
- test/unit/services/domain/expenses/test-refreshment-expense.js
- test/unit/services/domain/expenses/test-taxi-expense.js
- test/unit/services/domain/expenses/test-train-expense.js
- test/unit/services/routing/test-param-builder.js
- test/unit/services/validators/eligibility/test-expenses-validator.js
- Added unit tests for each of the expense domain objects.
- Added unit test for the expenses validator.
- Removed console.logs.
- Removed done calls.
> Added unit tests for each of the expense domain objects.

- app/views/start.html
chore - fix button on start page
The change I made to this button caused the ie8 e2e tests to fail
> chore - fix button on start page

- app/views/helpers/claim-expense-helper.js
- test/unit/views/helpers/test-claim-expense-helper.js
> chore - added test for claim-expense-helper

- test/e2e/spec.js
> chore - updated e2e to use donotsend@apvs.com

- app/services/data/insert-visitor.js
- migrations/20161107171431_remove-visitor-RequireBenefitUpload.js
- test/integration/services/data/test-insert-task-send-first-time-claim-notification.js
- test/integration/services/data/test-insert-visitor.js
> chore - removed Visitor.RequireBenefitUpload

- migrations/20161107171431_remove-visitor-RequireBenefitUpload.js
- migrations/20161108142655_add-additional-claim-expense-columns-2.js
- Added migration for adding the isChild column.
- Fixed a bug in the down function of the Visitor migration.
> Added migration for adding the isChild column.

- app/routes/first-time/eligibility/claim/accommodation-details.js
- app/routes/first-time/eligibility/claim/bank-account-details.js
- app/routes/first-time/eligibility/claim/bus-details.js
- app/routes/first-time/eligibility/claim/car-details.js
- app/routes/first-time/eligibility/claim/car-hire-details.js
- app/routes/first-time/eligibility/claim/claim-summary.js
- app/routes/first-time/eligibility/claim/ferry-details.js
- app/routes/first-time/eligibility/claim/light-refreshment-details.js
- app/routes/first-time/eligibility/claim/plane-details.js
- app/routes/first-time/eligibility/claim/taxi-details.js
- app/routes/first-time/eligibility/claim/train-details.js
- app/routes/first-time/eligibility/new-claim/journey-information.js
- app/routes/first-time/new-eligibility/about-the-prisoner.js
- app/routes/first-time/new-eligibility/about-you.js
chore - catch data layer errors in routes
fixes #141
> chore - catch data layer errors in routes

- app/services/data/get-claim-summary.js
> Simplified query

- app/routes/your-claims/your-claims.js
- app/views/your-claims/your-claims.html
- test/e2e/repeat-claim.js
- test/e2e/spec.js
- test/unit/routes/your-claims/test-your-claims.js
Added your-claim page.
- Added HTML.
- Added route.
- Added unit test.
- Page currently displays placeholder data.
- Added repeat claim end-to-end test.
- Added TODOs for remaining work.
> Feature/apvs 363/add view claims screen

- app/routes/first-time/eligibility/claim/accommodation-details.js
- app/routes/first-time/eligibility/claim/bus-details.js
- app/routes/first-time/eligibility/claim/car-details.js
- app/routes/first-time/eligibility/claim/car-hire-details.js
- app/routes/first-time/eligibility/claim/ferry-details.js
- app/routes/first-time/eligibility/claim/light-refreshment-details.js
- app/routes/first-time/eligibility/claim/plane-details.js
- app/routes/first-time/eligibility/claim/taxi-details.js
- app/routes/first-time/eligibility/claim/train-details.js
- app/services/domain/expenses/accommodation-expense.js
- app/services/domain/expenses/base-expense.js
- app/services/domain/expenses/bus-expense.js
- app/services/domain/expenses/car-expense.js
- app/services/domain/expenses/ferry-expense.js
- app/services/domain/expenses/hire-expense.js
- app/services/domain/expenses/plane-expense.js
- app/services/domain/expenses/refreshment-expense.js
- app/services/domain/expenses/taxi-expense.js
- app/services/domain/expenses/train-expense.js
- test/helpers/data/expense-helper.js
- test/unit/services/domain/expenses/test-accommodation-expense.js
- test/unit/services/domain/expenses/test-bus-expense.js
- test/unit/services/domain/expenses/test-car-expense.js
- test/unit/services/domain/expenses/test-ferry-expense.js
- test/unit/services/domain/expenses/test-hire-expenses.js
- test/unit/services/domain/expenses/test-plane-expense.js
- test/unit/services/domain/expenses/test-refreshment-expense.js
- test/unit/services/domain/expenses/test-taxi-expense.js
- test/unit/services/domain/expenses/test-train-expense.js
Removed claimId from the expense objects.
- Updated domain objects.
- Updated routes.
- Updated tests.
Closes #152.
> Remove claimId from the expense objects.

- docker-compose.yml
> chore - added missing envs to docker

- app/services/validators/validation-field-names.js
- app/views/first-time/eligibility/claim/about-child.html
Fixed validation display issues on about-child.
- child-name inline error now displays.
- dob error now displays between the inputs and the label rather than above the label.
- Field names are now lowercase after first word.
> Fixed validation display issues on about-child.

- app/services/upload.js
- config.js
> chore - env is string so limit must be parsed

- app/routes/first-time/eligibility/claim/claim-summary.js
- app/services/data/get-claim-summary.js
- app/services/data/remove-claim-document.js
- app/views/first-time/eligibility/claim/claim-summary.html
- test/helpers/data/claim-document-helper.js
- test/integration/services/data/test-remove-claim-document.js
- test/unit/routes/first-time/eligibility/claim/test-claim-summary.js
Apvs 672 - remove file link on claim summary page
* Added remove link to page if file uploaded
* Added logic to route to call remove claim document
* Added integration to update claim document IsEnabled to be false
* Added logic to delete the file
* Updated unit tests for route
* Added integration test
> Feature/apvs 672/remove file link

- app/assets/sass/application.scss
- app/views/first-time/eligibility/claim/claim-summary.html
> Chore/ warning display css for post and upload later

- package.json
- test/wdio.conf.sauce.chrome.jenkins.js
> chore - added chrome saucelabs config

- app/routes/first-time/eligibility/claim/bank-account-details.js
- app/routes/index.js
- app/services/data/submit-first-time-claim.js
- migrations/20161115143504_add-claim-column-caseworker.js
- test/integration/services/data/test-submit-first-time-claim.js
- test/unit/routes/first-time/eligibility/claim/test-bank-account-details.js
- test/unit/routes/test-index.js
* Added route to set assisted digital caseworker in cookie
* Persist assisted digital caseworker on submit claim
> Feature/apvs 597/assisted digital caseworker

- app/routes/first-time/eligibility/claim/claim-summary.js
- app/services/domain/claim-summary.js
- app/services/validators/validation-field-names.js
- app/views/first-time/eligibility/claim/claim-summary.html
- test/unit/routes/first-time/eligibility/claim/test-claim-summary.js
- test/unit/services/domain/test-claim-summary.js
Added validation for benefit document being uploaded if needed
* Updated domain for claim summary
* Updated domain test
* Updated route
* Updated route test
* Added warning flag and id into html
Tests updated accordingly
> Feature/apvs-348: Validation for benefit document

- app/assets/sass/application.scss
- app/constants/benefits-enum.js
- app/routes/first-time/eligibility/claim/claim-summary.js
- app/routes/first-time/eligibility/claim/file-upload.js
- app/views/first-time/eligibility/claim/claim-summary.html
- app/views/first-time/eligibility/claim/file-upload.html
Apvs-348 - Added multiple document option for benefits
* Added multipage to benefits enum
* Altered html to incorporate multiple documents for two of the benefits
* Added query to file-upload to hide alternatives if it is a second page being uploaded
> Feature/apvs 348 - Added multiple document option for benefits

- app/assets/javascripts/upload-page.js
- app/assets/sass/application.scss
- app/routes/first-time/eligibility/claim/claim-summary.js
- app/views/first-time/eligibility/claim/claim-summary.html
- app/views/first-time/eligibility/claim/file-upload.html
- test/unit/routes/first-time/eligibility/claim/test-claim-summary.js
chore - visit confirmation upload UX changes
> Chore/visit confirmation upload UX changes

- migrations/20161116112744_add-get-historic-claims-function.js
> chore - updated migration to use config

- app/routes/first-time/eligibility/claim/claim-summary.js
- app/services/domain/claim-summary.js
- app/services/validators/validation-field-names.js
- app/views/first-time/eligibility/claim/claim-summary.html
- test/e2e/spec.js
- test/unit/services/domain/test-claim-summary.js
Added validation for receipt upload and updated e2e test
* Added validation on domain claim summary
* Updated domain test
* Added warnings to html
* Updated e2e test
> Feature/apvs 671 -  validation on claim expense documents

- app/constants/receipt-required-enum.js
- app/routes/first-time/eligibility/claim/claim-summary.js
- app/routes/first-time/eligibility/claim/file-upload.js
- app/services/domain/claim-summary.js
- app/views/first-time/eligibility/claim/claim-summary.html
- test/e2e/spec.js
Made receipt not needed on some expenses
* Added enum for whether it receipt is needed
* Added check to html
* Updated validation to not check for a receipt on those expenses
* Added line to fix validation on multipage
…n of multipage
> Chore/ Making receipt not needed on some expenses

- test/unit/routes/first-time/new-eligibility/test-about-the-prisoner.js
- test/unit/routes/first-time/new-eligibility/test-about-you.js
Added tests to cover the throw within the else.
> Added tests to cover the throw within the else.

- test/unit/routes/test-index.js
Index route test now uses the route helper.
Added a test for the else case. When the query parameter is not set.
Works towards issue #125.
> Index route test now uses the route helper.

- app/views/apply/eligibility/claim/accommodation-details.html
- app/views/apply/eligibility/claim/bus-details.html
- app/views/apply/eligibility/claim/car-hire-details.html
- app/views/apply/eligibility/claim/ferry-details.html
- app/views/apply/eligibility/claim/light-refreshment-details.html
- app/views/apply/eligibility/claim/plane-details.html
- app/views/apply/eligibility/claim/taxi-details.html
- app/views/apply/eligibility/claim/train-details.html
- app/views/partials/expenses/cost.html
Factored the cost HTML out into a partial.
Works towards issue #153.
> Factored the cost HTML out into a partial.

- app/views/apply/eligibility/claim/bus-details.html
- app/views/apply/eligibility/claim/ferry-details.html
- app/views/apply/eligibility/claim/plane-details.html
- app/views/apply/eligibility/claim/train-details.html
- app/views/partials/expenses/from.html
- app/views/partials/expenses/to.html
Factored the 'from' and 'to' HTML on the expense pages out into partials.
Closes #153.
> Factored the 'from' and 'to' HTML out into partials

- app/locales/cy.json
- app/views/index.html
Feature/ Apvs 598 - Added link to visit confirmation download page
> Feature/ Apvs 598 - Added link to visit confirmation download page

- app/views/index.html
> Fixed template error on index

- app/views/apply/eligibility/claim/file-upload.html
Added style changes to upload to be like internal upload
> Added style changes to upload to be like internal upload

- app/views/application-submitted.html
Added information to application submitted concerning post and upload later
…and upload later
> Feature/ Apvs 372 - display info for post and upload later options

- app/views/application-submitted.html
chore - update message on application summary
> chore - update message on application summary

- app/services/data/submit-claim.js
- app/services/log.js
- config.js
- package.json
> chore - added logstash logger

- app/app.js
- config.js
- package.json
> chore - added configurable basic auth

- app/app.js
> chore - add root url exception to basic auth for Azure gateway

- app/app.js
> moved basic auth to under static resources

- app/assets/javascripts/upload-page.js
- app/assets/sass/application.scss
- app/views/apply/eligibility/claim/file-upload.html
Ux changes for making file upload look better
> Ux changes for making file upload look better

- test/integration/services/data/test-submit-claim.js
chore - fix integration test
Creating a new Date for the comparison rather than modifying `currentDate`
> chore - fix integration test

- app/routes/your-claims/check-your-information.js
- app/routes/your-claims/your-claims.js
- app/views/your-claims/check-your-information.html
- app/views/your-claims/your-claims.html
chore - use display helper for prison name
Update to use display helper to show the display name of the prison rather than the value stored in the database.
> chore - use display helper for prison name

- app/routes/apply/eligibility/new-claim/journey-information.js
- app/services/data/insert-new-claim.js
- app/services/data/insert-repeat-duplicate-claim.js
- migrations/20161128121352_add-claim-type-to-claim.js
- test/helpers/data/claim-helper.js
- test/helpers/data/internal/internal-claim-helper.js
- test/integration/services/data/test-insert-new-claim.js
- test/integration/services/data/test-insert-repeat-duplicate-claim.js
- test/unit/routes/apply/eligibility/new-claim/test-journey-information.js
> chore - persist claim type with claim

- app/views/your-claims/check-your-information.html
- app/views/your-claims/update-contact-details.html
- test/e2e/repeat-claim-new-contact-details.js
> chore - updated e2e test to include changing contact details

- app/constants/claim-type-enum.js
- app/routes/apply/new-eligibility/about-the-prisoner.js
- app/routes/apply/new-eligibility/benefits.js
- app/routes/apply/new-eligibility/prisoner-relationship.js
- app/services/data/insert-new-eligibility-and-prisoner.js
- app/views/apply/new-eligibility/about-the-prisoner.html
- app/views/apply/new-eligibility/benefits.html
- app/views/apply/new-eligibility/prisoner-relationship.html
- app/views/your-claims/check-your-information.html
- test/e2e/repeat-new-eligibility.js
- test/integration/services/data/test-insert-new-eligibility-and-prisoner.js
- test/unit/routes/apply/new-eligibility/test-about-the-prisoner.js
- test/unit/routes/apply/new-eligibility/test-benefits.js
- test/unit/routes/apply/new-eligibility/test-prisoner-relationship.js
> apvs-673 - repeat claim with new eligibility

- app/constants/prisons-enum.js
- app/views/apply/new-eligibility/about-the-prisoner.html
- app/views/helpers/display-helper.js
chore - update prisons enum with Jersey and Guernsey
> chore - update prisons enum with Jersey and Guernsey

- app/constants/prisons-enum.js
> update prison enum for consistency

- test/helpers/data/claim-helper.js
> updated integration test helper to use dynamic date

- app/routes/apply/eligibility/new-claim/same-journey-as-last-claim.js
- app/views/apply/eligibility/new-claim/same-journey-as-last-claim.html
chore - fix template errors
Fixes e2e test
> chore - fix template errors

- test/wdio.conf.sauce.ie8.jenkins.js
- test/wdio.conf.sauce.ie8.js
chore - run ie8 test on Windows XP
> chore - run ie8 test on Windows XP

- test/e2e/repeat-claim-duplicate.js
- test/e2e/repeat-claim-new-contact-details.js
- test/e2e/repeat-new-eligibility.js
> chore - updated e2e test descriptions

- app/assets/javascripts/ga.js
- app/views/includes/head.html
- package.json
> apvs-675 - added google analytics to site layout

- test/helpers/data/internal/internal-claim-helper.js
> set Claim.DateReviewed in test data so it can be used in auto approvals

- app/routes/apply/new-eligibility/benefits.js
> bug - benefit screen was displaying wrong view on validation error

- .gitignore
- app/app.js
- app/services/domain/about-child.js
- app/services/domain/about-the-prisoner.js
- app/services/domain/about-you.js
- app/services/domain/expenses/base-expense.js
- cache_node_modules/.gitignore
- package.json
- test/helpers/routes/route-helper.js
- test/unit/services/domain/expenses/test-train-expense.js
- test/unit/services/domain/test-about-child.js
- test/unit/services/domain/test-about-the-prisoner.js
- test/unit/services/domain/test-about-you.js
apvs-822 - Adding request sanitization to external request params and tightened validation around free text input fields
> Issue/apvs 822/request sanitiser

- app/routes/your-claims/view-claim.js
- app/views/partials/claim-summary/claim-summary-expenses.html
- app/views/your-claims/your-claims.html
- test/e2e/upload-later-send-message.js
- test/helpers/data/internal/internal-claim-document-helper.js
- test/helpers/data/internal/internal-claim-helper.js
- test/helpers/data/internal/internal-eligibility-helper.js
- test/integration/services/data/test-get-claim-documents-historic-claim.js
Added e2e test for upload later flow
Also removed remove expense on view claim
Also removed remove expense list on view claim
> Feature/ apvs 373/ e2e test on upload later flow

- app/app.js
- config.js
apvs-925: Updating security header configuration, including:
- Secure cookie settings
- Content Security Policy
- Review of Helmet default configuration
- New environment variables included for cookie security
> Issue/apvs 925/sec headers

- app/assets/sass/application.scss
- app/constants/claim-decision-enum.js
- app/constants/claim-event-enum.js
- app/routes/helpers/for-edit.js
- app/routes/your-claims/view-claim.js
- app/services/data/get-claim-events.js
- app/services/data/get-view-claim.js
- app/services/data/insert-repeat-duplicate-claim.js
- app/services/domain/view-claim.js
- app/services/helpers/sort-view-claim-results-helper.js
- app/services/validators/validation-field-names.js
- app/views/helpers/claim-event-helper.js
- app/views/partials/claim-summary/claim-summary-events.html
- app/views/partials/claim-summary/claim-summary-expenses.html
- app/views/partials/claim-summary/claim-summary-visit.html
- app/views/partials/claim-summary/claim-summary-visitor.html
- app/views/your-claims/view-claim.html
- migrations/20161212105503_update-get-historic-claim-return-visit-confirmation-and-benefit-status.js
- migrations/20161212114840_update-get-claim-expense-by-id-or-last-approved-with-status.js
- migrations/20161212123441_add-get-claim-events-by-claim-id.js
- test/helpers/data/internal/internal-claim-event-helper.js
- test/helpers/data/internal/internal-eligibility-helper.js
- test/integration/services/data/test-get-claim-documents-historic-claim.js
- test/integration/services/data/test-get-claim-events.js
- test/unit/routes/helpers/test-for-edit.js
- test/unit/services/data/test-get-view-claim.js
- test/unit/services/helpers/test-sort-claim-results-helper.js
- test/unit/views/helpers/test-claim-event-helper.js
- test/unit/views/helpers/test-claim-status-helper.js
Added request information views and showing the claim events
* Made read only view claim for certain status'
* Table function for claim events
* Updated table functions to get status
* Call for claim events
* Viewing claim events
* Views for request information
> Feature/apvs 373/request information and claim events

- app/views/partials/claim-summary/claim-summary-visitor.html
> corrected label

- app/routes/helpers/for-edit.js
- app/routes/your-claims/view-claim.js
- app/routes/your-claims/your-claims.js
- app/services/helpers/sort-view-claim-results-helper.js
- app/views/partials/claim-summary/claim-summary-expenses.html
- app/views/partials/claim-summary/claim-summary-visit.html
- app/views/your-claims/your-claims.html
- test/unit/routes/helpers/test-for-edit.js
- test/unit/services/helpers/test-sort-claim-results-helper.js
Added ability for uploading later or for request information on advance claims
* Updated forEdit to include advance claims that are approved
* Updated forEdit test
* Added function to sort helper to add temporary placeholder documents on advance claim
* Updated sort helper test to check advance claims
* Updated html partials for visit confirmation and expense receipts
> Feature/apvs 231/adding information for advance claim

- app/assets/sass/application.scss
- app/routes/helpers/for-edit.js
- app/routes/your-claims/view-claim.js
- app/services/data/get-historic-claims.js
- app/views/partials/claim-summary/claim-summary-expenses.html
- app/views/partials/claim-summary/claim-summary-visit.html
- app/views/your-claims/your-claims.html
- migrations/20161219103900_update-get-historic-claim-to-return-date-submitted.js
- test/unit/routes/helpers/test-for-edit.js
Added fixes to issues that Chris opened
* closes issues #270 #269 
* Updated forEdit to check date of journey so advance only editable after the date
> Chore/ your claims and view claim display issues

- app/constants/claim-decision-enum.js
- app/views/partials/claim-summary/claim-summary-expenses.html
- test/unit/views/helpers/test-claim-status-helper.js
> Fixed issue #271 showing approved different amount

- .gitignore
- migrations/20161123164459_add-get-last-claim-expenses-function.js
- migrations/20161219144722_update-get-historic-claims-approved-cost.js
Altered the table function to retrieve ApprovedCost rather than Cost.
Updated gitignore to include local scripts.
Added TODO to remove unused migration file. An issue will be raised to track this.
Closes #272.
> Altered the table function to retrieve ApprovedCost rather than Cost.

- app/routes/apply/new-eligibility/about-you.js
- app/services/data/insert-visitor.js
- app/services/domain/about-you.js
- app/services/validators/validation-field-names.js
- app/views/apply/new-eligibility/about-you.html
- app/views/your-claims/check-your-information.html
- migrations/20161121145331_add-get-masked-eligibility-function.js
- migrations/20161214174648_drop-visitor-column-title.js
- migrations/20161214175534_update-get-masked-eligibility-function.js
- test/e2e/first-time-advance-claim.js
- test/e2e/first-time-claim.js
- test/e2e/repeat-new-eligibility.js
- test/helpers/data/internal/internal-visitor-helper.js
- test/helpers/data/visitor-helper.js
- test/unit/services/domain/test-about-you.js
> chore - remove title

- migrations/20161221121204_add-claim-escort.js
> Adding escort table.

- app/views/apply/eligibility/claim/bank-account-details.html
> Chore/ fix id error

- app/constants/expense-type-enum.js
- app/constants/expenses-url-path-enum.js
- app/constants/helpers/prisons-helper.js
- app/routes/apply/eligibility/claim/car-details.js
- app/routes/apply/eligibility/claim/expenses.js
- app/views/apply/eligibility/claim/car-details.html
- app/views/apply/eligibility/claim/expenses.html
- app/views/partials/expenses/expenses-list-ni.html
- app/views/partials/expenses/expenses-list.html
- test/e2e/first-time-claim-ni.js
- test/unit/constants/helpers/test-prisons-helper.js
- test/unit/routes/apply/eligibility/claim/test-car-details.js
- test/unit/routes/apply/eligibility/claim/test-expenses.js
- does not include advance claim restriction which is covered in 968
> apvs-969 - restrict expenses for NI claims

- app/services/validators/validation-field-names.js
- test/unit/services/domain/test-bank-account-details.js
> fixed typo in display text

- app/app.js
Update page <title> to 'Get help with prison visits' #315
> Chore/Update page <title> to 'Get help with prison visits'

- app/views/apply/eligibility/new-claim/journey-information.html
> chore/ Minor content changes to journey information page

- app/services/data/insert-escort.js
- test/helpers/data/claim-escort-helper.js
- test/integration/services/data/test-insert-escort.js
> bug-312 - mark previous escorts as disabled so user cannot add multiple

- test/e2e/first-time-advance-claim.js
- test/e2e/first-time-claim-ni.js
- test/e2e/first-time-claim.js
- test/e2e/repeat-claim-duplicate.js
- test/e2e/repeat-claim-new-contact-details.js
- test/e2e/repeat-new-eligibility.js
- test/e2e/update-claim-bank-details.js
- test/e2e/upload-later-send-message.js
- test/helpers/data/internal/internal-eligibility-helper.js
- test/helpers/e2e/reference-helper.js
All end-to-end tests now cleanup after themselves. 
As we have tests that insert records into both the External and Internal databases the delete function removes all records with the given reference from both.
Closes #311.
> Clean up data after the tests complete.

- app/constants/claim-decision-enum.js
> Bug - display AUTO-APPROVED decision as Approved in Your Claims

- app/constants/expense-type-enum.js
- app/services/data/disable-non-ticketed-expenses-for-claim.js
- app/services/data/insert-expense.js
- app/views/apply/eligibility/claim/accommodation-details.html
- app/views/apply/eligibility/claim/car-details.html
- app/views/apply/eligibility/claim/car-hire-details.html
- app/views/apply/eligibility/claim/light-refreshment-details.html
- test/helpers/data/expense-helper.js
- test/integration/services/data/test-disable-non-ticketed-expenses-for-claim.js
- test/integration/services/data/test-insert-expense.js
> bug 282 - prevent users adding multiple non-ticketed expenses

- README.md
- app/constants/payment-method-enum.js
- app/routes/apply/eligibility/claim/bank-account-details.js
- app/services/data/submit-claim.js
- migrations/20170119110223_add-payment-method-to-claim.js
- test/integration/services/data/test-submit-claim.js
- test/unit/routes/apply/eligibility/claim/test-bank-account-details.js
- Updated readme with details about how payment methods should work, and what to look out for when adding new payment methods
- Added payment-method-enum 
- Added code to default PaymentMethod when bank account details are submitted
> Feature/apvs 1026/payment method

- app/views/apply/new-eligibility/benefits.html
> Removed "Please select from the following options:" from benefits page

- app/assets/sass/application.scss
- app/views/apply/new-eligibility/about-you.html
Changed 'p' element to 'span' because it was pushing content down the page.
Closes #359
> Fixed spacing issue on About You page

- app/views/apply/eligibility/claim/expenses.html
> Updated displayed text.

- test/unit/routes/test-technical-help.js
Brings coverage for the file to 100%.
> Added unit test to cover untested branch.

- test/unit/routes/test-start-already-registered.js
Brings the code coverage up to 100% for the route.
> Added unit test to cover untested branch in start-already-registered.

- test/unit/routes/health-check/test-status.js
Simplified the health check status unit test.
Brought code coverage to 100%.
> Simplified the health check status unit test

- app/constants/ticket-owner-enum.js
- app/views/apply/eligibility/claim/about-escort.html
- app/views/apply/eligibility/claim/has-escort.html
- app/views/index.html
- app/views/partials/claim-summary/claim-summary-visitor.html
> content update - change carer to escort

- test/unit/services/domain/expenses/test-train-expense.js
Add a test to cover the case where a train expense is an advance claim.
Brought test coverage to 100%.
> Add a test to cover the case where a train expense is an advance claim

- app/services/validators/error-handler.js
- test/unit/services/validators/test-error-handler.js
Removed unnecessary check in the error handler. We were iterating over the fields and checking that field existed.
Removed done calls.
Added a unit test to cover the case of zero length fields. 
Brings code coverage up to 100%.
> Updated error-handler unit tests

- app/views/your-claims/your-claims.html
> Show correct claim status for Rejected advance claims

- test/unit/services/helpers/test-encrypt.js
Added tests to cover untested branches.
Brings test coverage up to 100%.
> Updated unit tests for encrypt

- app/assets/sass/application.scss
Should fix re-occurrence of #359
> Re-added prevent-margin-collapse class

- app/views/your-claims/your-claims.html
> Moved Start new claim button below header, moved error message below button

- app/constants/benefits-enum.js
- app/routes/apply/new-eligibility/about-you.js
- app/services/validators/common-validator.js
- app/views/apply/new-eligibility/benefits.html
- test/unit/routes/apply/new-eligibility/test-about-the-prisoner.js
- test/unit/routes/apply/new-eligibility/test-about-you.js
- test/unit/routes/apply/new-eligibility/test-benefits.js
- test/unit/services/domain/test-benefits.js
- test/unit/services/validators/test-common-validator.js
- test/unit/services/validators/test-field-validator.js
- test/unit/services/validators/test-url-path-validator.js
Added urlValue to benefit so when it is a param in the url it is abstracted
* Added urlValue to html and benefits enum
* Added the urlValue to check to validation
> Feature/apvs 1062/add benefit url enum

- app/views/partials/claim-summary/claim-summary-expenses.html
- app/views/your-claims/view-claim.html
> Added check to show table only when claim expenses exist

- app/views/apply/eligibility/claim/has-child.html
> chore - update has-child page content

- app/assets/javascripts/print-link.js
- app/views/application-submitted.html
- app/views/includes/scripts.html
> moved print javascript to script to fix CSP issues

- app/views/eligibility-fail.html
> chore - update eligibility fail page content

- app/views/apply/eligibility/new-claim/same-journey-as-last-claim.html
> removed unnecessary br tags

- app/routes/helpers/get-required-information-warnings.js
related to #439 but will not fix issue with failed async worker task not copying claim documents
> added check to ensure document object is present

- app/routes/apply/new-eligibility/about-you.js
- app/routes/apply/new-eligibility/date-of-birth.js
- app/routes/start-already-registered.js
- app/routes/your-claims/check-your-information.js
- app/routes/your-claims/view-claim.js
- app/routes/your-claims/your-claims.js
- app/services/date-formatter.js
- app/services/domain/already-registered.js
- app/services/domain/date-of-birth.js
- app/services/validators/url-path-validator.js
- app/views/your-claims/view-claim.html
- test/unit/routes/apply/new-eligibility/test-about-the-prisoner.js
- test/unit/routes/apply/new-eligibility/test-about-you.js
- test/unit/routes/apply/new-eligibility/test-benefits.js
- test/unit/routes/apply/new-eligibility/test-date-of-birth.js
- test/unit/routes/apply/new-eligibility/test-prisoner-relationship.js
- test/unit/routes/test-start-already-registered.js
- test/unit/routes/your-claims/test-check-your-information.js
- test/unit/routes/your-claims/test-update-contact-details.js
- test/unit/routes/your-claims/test-view-claim.js
- test/unit/routes/your-claims/test-your-claims.js
- test/unit/services/domain/test-already-registered.js
- test/unit/services/domain/test-date-of-birth.js
- test/unit/services/test-date-formatter.js
- test/unit/services/validators/test-url-path-validator.js
Added a feature to encode and decode the dob in the url
* Added encode and decode in date formatter
* Added an encode to dob post route
* Added decode to all routes which used dob to insert and fetch data
* Added decode for dob in url validator
> Feature/apvs 1062/encode dob in url

- app/assets/sass/application.scss
> chore - update beta banner colour

- app/services/directory-check.js
- test/unit/services/test-directory-check.js
Added a unit test to cover an untested branch.
Made requires constants.
Gave constants constant style names.
Brings test coverage up to 100%.
> Updated directory-check unit tests

- app/services/domain/about-you.js
- app/services/validators/field-validator.js
- test/unit/services/validators/test-field-validator.js
chore - fix country field validation
Re-adding the check that a value for country has been selected.
> chore - fix country field validation

- app/views/start-already-registered.html
- test/e2e-smoke/already-registered-smoke.js
- test/e2e/repeat-claim-duplicate.js
- test/e2e/repeat-claim-new-contact-details.js
- test/e2e/repeat-new-eligibility.js
- test/e2e/update-claim-bank-details.js
- test/e2e/upload-later-send-message.js
> Added reference id to div so validation link scrolls to correct location

- app/views/apply/new-eligibility/about-the-prisoner.html
> set blank value for default name of prison

- test/load/scenarios.yaml
> updated performance tests for new url path params

- test/unit/services/domain/test-about-the-prisoner.js
- test/unit/services/domain/test-about-you.js
Adding a check that validation messages are returned for required fields in the domain object
Relates to #469 
> Update about-you and about-the-prisoner domain tests

- app/routes/apply/eligibility/claim/light-refreshment-details.js
- app/services/domain/expenses/refreshment-expense.js
- app/views/apply/eligibility/claim/light-refreshment-details.html
- app/views/helpers/claim-expense-helper.js
- app/views/partials/expenses/cost.html
- test/e2e/first-time-claim.js
- test/load/scenarios.yaml
- test/unit/services/domain/expenses/test-refreshment-expense.js
- test/unit/views/helpers/test-claim-expense-helper.js
Updated light refreshment to take out time and update text 
* Updated html
* Updated route calling domain
* Updated domain to no longer use time
* Updated display helper to show nothing on empty text
* Updated e2e first time flow test
* Updated performance test
> Feature/apvs 1082/update light refreshment page

- app/services/data/get-claim-summary.js
- app/services/data/get-last-claim-details.js
- test/unit/services/data/test-get-last-claim-details.js
> Masked escort returned on repeat duplicate

- app/app.js
- app/views/apply/eligibility/claim/bank-account-details.html
- app/views/apply/eligibility/claim/claim-summary.html
- app/views/includes/phase_banner_beta.html
- app/views/index.html
Updated some of the content after martins content review.
Chris opened a issue #392
> Chore/update content after GDS review

- app/services/data/get-claim-summary.js
> Added check for escort existing on claim duplicate

- app/routes/apply/eligibility/claim/expenses.js
- app/routes/apply/new-eligibility/about-you.js
- app/routes/your-claims/check-your-information.js
- app/services/data/get-claim-summary.js
- test/e2e/first-time-advance-claim.js
- test/e2e/first-time-claim-ni.js
- test/e2e/first-time-claim.js
- test/unit/routes/apply/eligibility/claim/test-expenses.js
- test/unit/routes/apply/new-eligibility/test-about-you.js
- test/unit/routes/your-claims/test-check-your-information.js
Updated the way NI rules works
* Updated expenses to use country rather than prison
* Updated redirection on about you and check your info to also use country
* Updated e2e tests
> Feature/apvs 1052/change ni rules based on country

- app/views/apply/new-eligibility/benefits.html
- app/views/apply/new-eligibility/prisoner-relationship.html
Made content changes
* Changes to ESA and UC benefits text
* Changes to sole visitor relationship
> Feature/apvs 1187/content changes

- app/app.js
> Changed addition of empty object

- app/constants/payment-method-enum.js
- app/routes/apply/eligibility/claim/bank-account-details.js
- app/routes/apply/eligibility/claim/claim-summary.js
- app/routes/apply/eligibility/claim/payment-details-and-declaration.js
- app/routes/routes.js
- app/services/data/get-address.js
- app/services/data/insert-bank-account-details-for-claim.js
- app/services/data/submit-update.js
- app/services/domain/payment-details.js
- app/views/apply/eligibility/claim/bank-account-details.html
- app/views/apply/eligibility/claim/payment-details-and-declaration.html
- config.js
- test/e2e/first-time-advance-claim.js
- test/e2e/first-time-claim-ni.js
- test/e2e/first-time-claim.js
- test/e2e/repeat-claim-duplicate.js
- test/e2e/repeat-claim-new-contact-details.js
- test/e2e/repeat-new-eligibility.js
- test/helpers/data/bank-helper.js
- test/integration/services/data/test-get-address.js
- test/unit/routes/apply/eligibility/claim/test-bank-account-details.js
- test/unit/routes/apply/eligibility/claim/test-claim-summary.js
- test/unit/routes/apply/eligibility/claim/test-payment-details-and-declaration.js
- test/unit/services/data/test-submit-update.js
- test/unit/services/domain/test-bank-account-details.js
- test/unit/services/domain/test-payment-details.js
Added the payout option to external with a config value to turn it off and on
* Config toggle for including payout method
* New html for payment details and declaration (copying parts of bank details)
* New route for payment details and declaration (copying parts of bank details)
* Updated and renamed domain to take into account payout option
> Feature/apvs 1177/payout option

- app/constants/benefits-enum.js
- app/constants/document-type-enum.js
> Added universal credit to doc type & updated benefit enum

- test/e2e/first-time-advance-claim-ni.js
> Added advance claim ni e2e test flow

- app/assets/sass/application.scss
- app/views/apply/eligibility/claim/file-upload.html
Works for chrome, works in firefox (does not highlight when tabbed over but it is accessible for keyboard only)
Needs tested in IE
> Possible fix for tabbing to file input

- app/routes/apply/eligibility/claim/about-escort.js
- app/services/data/insert-escort.js
- app/services/domain/about-escort.js
- app/views/apply/eligibility/claim/about-escort.html
- migrations/20170303120438_remove-escort-national-insurance-number.js
- test/e2e/first-time-claim.js
- test/helpers/data/claim-escort-helper.js
- test/integration/services/data/test-insert-escort.js
- test/unit/services/domain/test-about-escort.js
Removed NIN from escort
* Added migration to remove NIN from escort
* Updated insert escort to remove NIN
* Updated domain to remove NIN
* Updated view and route removing NIN
* Updated e2e test
> Feature/apvs 1276/remove escort nin

- app/views/apply/eligibility/claim/about-child.html
- app/views/apply/eligibility/claim/file-upload.html
- app/views/apply/eligibility/claim/has-child.html
- app/views/apply/eligibility/claim/has-escort.html
- app/views/apply/eligibility/new-claim/future-or-past-visit.html
- app/views/apply/eligibility/new-claim/journey-information.html
- app/views/apply/eligibility/new-claim/same-journey-as-last-claim.html
- app/views/apply/new-eligibility/about-you.html
- app/views/apply/new-eligibility/benefits.html
- app/views/apply/new-eligibility/date-of-birth.html
- app/views/apply/new-eligibility/prisoner-relationship.html
- app/views/feedback.html
- app/views/partials/expenses/return-journey.html
- app/views/partials/expenses/ticket-owner.html
- app/views/start.html
Added in legends for fieldsets that were missing them
> Feature/apvs 1338/dac fieldsets legends and optional hint text

- app/views/apply/eligibility/claim/file-upload.html
- app/views/apply/eligibility/claim/payment-details-and-declaration.html
- app/views/start-already-registered.html
> Removed fields added by gov javascript

- app/assets/javascripts/disable-button-after-submit.js
- app/views/includes/scripts.html
Added front end JS to prevent double submission to complement server side prevention
> Feature/apvs 1426/frontend js preventing double submission

- app/routes/apply/eligibility/claim/car-details.js
- app/services/data/insert-expense.js
- app/services/domain/expenses/base-expense.js
- app/services/domain/expenses/car-expense.js
- app/services/validators/validation-error-messages.js
- app/views/apply/eligibility/claim/car-details.html
- app/views/helpers/display-helper.js
- test/unit/services/domain/expenses/test-car-expense.js
- test/unit/views/helpers/test-display-helper.js
Updated car journey to take a new destination as an alternative to going straight to prison
* Added options to view
* Updated route to send inputs to domain
* Updated domain to replace to and take new option of toPostCode
* Updated base expense domain to take toPostCode
* Updated insert expense to update toPostCode if appropriate
*Updated display helper to return input value if no prison value found instead of undefined
> Feature/apvs 1399/update to car journey for another route

- app/routes/apply/eligibility/claim/payment-details.js
- app/routes/helpers/get-change-address-link.js
- app/services/data/get-address-and-link-details.js
- app/views/apply/eligibility/claim/payment-details.html
- test/integration/services/data/test-get-address.js
- test/unit/routes/apply/eligibility/claim/test-payment-details.js
- test/unit/routes/helpers/test-get-change-address-link.js
Added change address link to payment page
* Updated get address to now return details needed for first time claim change address link
* Added module to get what link is required to change address
* Added link to html
> Feature/apvs 1464/add change address link

- app/routes/technical-help.js
- app/views/eligibility-fail.html
- app/views/includes/phase_banner_beta.html
- app/views/technical-help.html
- test/unit/routes/test-technical-help.js
> Renaming /technical-help to /help

- app/routes/apply/eligibility/new-claim/same-journey-as-last-claim.js
> Removing redirect loop for repeat users with rejected claims

- app/views/apply/new-eligibility/prisoner-relationship.html
> APVS-0033: change display text on prisoner-relationship page.

- app/constants/claim-event-enum.js
> APVS-0036: New enum to show correct text for close-advance-claims event.

- app/services/data/insert-new-eligibility-and-prisoner.js
- app/services/data/insert-visitor.js
> Feature/apvs 0034/updating existing details

- app/views/includes/layout.html
> Updating feedback and help links

- app/views/apply/new-eligibility/about-you.html
> Adding examples

- app/routes/apply/eligibility/new-claim/journey-information.js
- app/services/domain/new-claim.js
- app/views/apply/eligibility/new-claim/journey-information.html
- test/unit/services/domain/test-new-claim.js
> Increasing max days from 28 to 99

- app/views/technical-help.html
> Updating help text

- app/routes/apply/eligibility/claim/file-upload.js
- app/services/move-file.js
- test/integration/services/test-move-file.js
> Issue/apvs 0025/file upload error

- app/routes/application-submitted.js
- app/services/data/submit-claim.js
> Feature/apvs 0061/kibana logging change

- app/constants/benefits-enum.js
- app/routes/helpers/get-required-information-warnings.js
> Allowing auto check for pensions credit

- app/views/partials/claim-summary/claim-summary-visit.html
> Feature/apvs 0070/visit confirmation in review

- app/constants/benefits-enum.js
> Removing DWP check for pension credit

- app/services/data/get-claim-expense-by-id-or-last-approved.js
> Feature/apvs 0089/error on submitting a claim

- app/constants/document-type-enum.js
- app/views/partials/claim-summary/claim-summary-visitor.html
Updating document type definitions
Changing condition for document upload functionality to be enabled
> Feature/apvs 0062/dwp fail auto email

- app/services/data/disable-non-ticketed-expenses-for-claim.js
- app/services/data/insert-expense.js
- test/helpers/data/claim-document-helper.js
- test/integration/services/data/test-disable-non-ticketed-expenses-for-claim.js
> Feature/apvs 0076/document upload issues

- app/views/partials/claim-summary/claim-summary-visitor.html
Removing DWP benefit checker result conditions on displaying the benefit documentation upload
> Removing dwp benefit checker result conditions

- app/views/partials/claim-summary/claim-summary-visitor.html
Including upload later as a condition
> Changing condition on benefit upload being displayed

- app/constants/benefits-enum.js
Updating income support, jobseekers allowance and employment support to allow multipage uploads (APVS0062-16)
> Updating income, jsa and employment to allow multipage upload

- app/assets/sass/application.scss
- app/views/apply/eligibility/claim/payment-details.html
> Feature/apvs 0099/hide bank payments option

- app/routes/apply/eligibility/claim/declaration.js
- app/routes/apply/eligibility/claim/train-details.js
- app/services/domain/expenses/accommodation-expense.js
- app/services/domain/expenses/bus-expense.js
- app/services/domain/expenses/car-expense.js
- app/services/domain/expenses/ferry-expense.js
- app/services/domain/expenses/hire-expense.js
- app/services/domain/expenses/plane-expense.js
- app/services/domain/expenses/refreshment-expense.js
- app/services/domain/expenses/taxi-expense.js
- app/services/domain/expenses/train-expense.js
- app/services/validators/common-validator.js
- app/services/validators/error-handler.js
- app/services/validators/field-validator.js
- app/services/validators/fieldset-validator.js
- app/services/validators/validation-error-messages.js
- config.js
> Feature/apvs 0058/additional field validation

- app/services/domain/new-claim.js
- app/views/apply/eligibility/new-claim/journey-information.html
- config.js
- test/unit/services/domain/test-new-claim.js
> Feature/apvs 0125/reduce claim window

- app/services/domain/new-claim.js
- test/unit/services/domain/test-new-claim.js
> Fix/apvs 0127/input date returning previous days date

- app/services/data/insert-new-eligibility-and-prisoner.js
- package.json
> Fix/apvs 0182/update prison name

- app/constants/prisons-enum.js
> APVS0182: Removing the HMP prefix from the Humber prison

- test/helpers/data/internal/internal-visitor-helper.js
- test/helpers/data/visitor-helper.js
> Fixing integration tests

- app/routes/apply/eligibility/new-claim/same-journey-as-last-claim.js
- app/services/data/get-last-claim-details.js
- app/services/data/insert-repeat-duplicate-claim.js
- test/unit/services/data/test-get-last-claim-details.js
> Fix/apvs 0202/approved cost different when claim is assigned

- app/constants/benefits-enum.js
> Fix/apvs 0201/uploading multiple documents

- app/routes/apply/eligibility/claim/declaration.js
- app/routes/start-already-registered.js
- app/services/data/check-if-reference-is-disabled.js
- app/services/validators/session-handler.js
- app/services/validators/validation-error-messages.js
- test/unit/routes/apply/eligibility/claim/test-declaration.js
> Feature/apvs 0164/disable reference with wrong nino

- test/e2e/first-time-advance-claim-ni.js
- test/e2e/first-time-advance-claim.js
- test/e2e/first-time-claim-ni.js
- test/e2e/first-time-claim.js
- test/e2e/repeat-new-eligibility.js
> APVS0164: Fixing e2e tests

- app/routes/apply/eligibility/new-claim/journey-information.js
- app/services/data/visitor-prisoner-check.js
- test/unit/routes/apply/eligibility/new-claim/test-journey-information.js
> Adding check for visit on the same day

- app/routes/apply/eligibility/new-claim/journey-information.js
- app/services/domain/new-claim.js
- app/services/validators/fieldset-validator.js
- app/services/validators/validation-error-messages.js
- app/views/apply/eligibility/new-claim/journey-information.html
- test/unit/routes/apply/eligibility/new-claim/test-journey-information.js
- test/unit/services/domain/test-new-claim.js
> Changing format of error

- app/services/domain/benefit-owner.js
- app/services/validators/validation-error-messages.js
- app/views/apply/new-eligibility/benefit-owner.html
> Fix/apvs 0211/incorrect benefit owner error messages

- app/assets/javascripts/ga.js
> Adding routing to gov.uk for google analytics

- app/assets/javascripts/ga.js
> Updating to add gov.uk

- app/routes/apply/eligibility/new-claim/journey-information.js
- app/services/data/get-release-date.js
- app/services/domain/new-claim.js
- app/services/validators/common-validator.js
- app/services/validators/fieldset-validator.js
- app/services/validators/validation-error-messages.js
- npm-shrinkwrap.json
- test/unit/routes/apply/eligibility/new-claim/test-journey-information.js
- test/unit/services/domain/test-new-claim.js
> Feature/apvs 0196/inclusion of prisoner release date

- app/constants/prisoner-relationships-enum.js
- app/routes/apply/new-eligibility/benefits.js
- app/views/apply/new-eligibility/benefits.html
- app/views/apply/new-eligibility/prisoner-relationship.html
- test/unit/routes/apply/new-eligibility/test-prisoner-relationship.js
> Feature/apvs 0210/child escorts

- app/routes/apply/new-eligibility/about-the-prisoner.js
> APVS0210: Fixing an issue where the eligble child page is not shown

- app/routes/apply/new-eligibility/benefit-owner.js
- test/unit/routes/apply/new-eligibility/test-benefit-owner.js
> Fix/apvs 0226/benefit owner issue

- app/views/apply/new-eligibility/benefits.html
> APVS0210: Fixing eligible child benefit question

- test/helpers/data/bank-helper.js
- test/integration/services/data/test-insert-bank-account-details-for-claim.js
> APVS0016: Fixing integration tests

- test/e2e/first-time-advance-claim-ni.js
- test/e2e/first-time-advance-claim.js
- test/e2e/first-time-claim-ni.js
- test/e2e/first-time-claim.js
- test/e2e/repeat-claim-duplicate.js
- test/e2e/repeat-claim-new-contact-details.js
- test/e2e/repeat-new-eligibility.js
- test/e2e/update-claim-bank-details.js
> APVS0016: Updating e2e tests

- app/services/domain/new-claim.js
> APVS0196: Removing release date restriction from external web

- test/integration/services/data/test-get-claim-summary.js
- test/integration/services/test-move-file.js
> APVS0215: Fixing integration tests

- package-lock.json
- test/wdio.conf.sauce.chrome.jenkins.js
- test/wdio.conf.sauce.chrome.jenkins.smoke.js
- test/wdio.conf.sauce.firefox.jenkins.js
- test/wdio.conf.sauce.firefox.js
> Feature/apvs 0215/node version upgrade

- package-lock.json
- package.json
> APVS0245: Removing gulp-install

- package-lock.json
- package.json
> WMT0213: Downgrading wdio to version 6.10.5

- .circleci/config.yml
- .dockerignore
- .gitignore
- Dockerfile
- app/bin/www
- app/bin/www-maintenance
- app/services/clam-av.js
- config.js
- docker-compose.yml
- package-lock.json
- package.json
> HWPV-17: Allow application to run in Docker

- helm_deploy/help-with-prison-visits-external/Chart.yaml
- helm_deploy/help-with-prison-visits-external/values.yaml
> Add clamav dependancy chart

- .circleci/config.yml
- Dockerfile
- package-lock.json
Switch back to node 12 for compatibility
> Switch back to node 12 for compatibility on old service

- seeds/add-get-claim-children-by-id-or-last-approved-function.js
- seeds/add-get-claim-documents-historic-claim.js
- seeds/add-get-claim-escort-by-id-or-last-approved.js
- seeds/add-get-claim-events-function.js
- seeds/add-get-claim-expense-by-id-or-last-approved.js
- seeds/add-get-historic-claims-function.js
- seeds/add-get-masked-eligibility-function.js
- seeds/add-get-references-for-duplicate-check.js
These functions all apply to the external user so not sure why they were in the internal app.
> Add seeds folder for external user

- helm_deploy/help-with-prison-visits-external/Chart.yaml
- helm_deploy/help-with-prison-visits-external/values.yaml
Changes for cloud platform, as discussed on [Slack](https://mojdt.slack.com/archives/C69NWE339/p1634027249194400)
> VB-274: Use new generic service configuration

- app/services/nunjucks-setup.js
Should fix the 500 errors relating to template rendering.
> Fix 'findError' Nunjucks filter

- app/assets/javascripts/upload-page.js
- app/views/apply/eligibility/claim/bank-payment-details.html
- app/views/apply/eligibility/claim/bus-details.html
- app/views/apply/eligibility/claim/car-details.html
- app/views/apply/eligibility/claim/claim-summary.html
- app/views/apply/eligibility/claim/declaration.html
- app/views/apply/eligibility/claim/expenses.html
- app/views/apply/eligibility/claim/file-upload.html
- app/views/apply/eligibility/claim/light-refreshment-details.html
Some partial views remain unconverted in `app/views/partials/expenses` - these will be picked up in subsequent tickets for the other flows.
> VB-340 Move remaining screens in first-time claim flow to new GDS

- app/views/partials/claim-summary/claim-summary-expenses.html
- app/views/partials/claim-summary/claim-summary-visit.html
- app/views/partials/claim-summary/claim-summary-visitor.html
- app/views/your-claims/check-your-information.html
- test/cypress-e2e/integration/first-time-advance-claim-ni-spec.js
- test/cypress-e2e/integration/first-time-advance-claim-ni-voucher-spec.js
- test/cypress-e2e/integration/first-time-advance-claim-spec.js
- test/cypress-e2e/integration/first-time-claim-ni-spec.js
- test/cypress-e2e/integration/first-time-claim-spec.js
- test/cypress-e2e/integration/repeat-claim-duplicate-spec.js
- test/cypress-e2e/integration/repeat-claim-new-contact-details-spec.js
- test/helpers/data/internal/internal-visitor-helper.js
Test elements on summary pages to make sure the correct data has actually come through - doing in advance of moving the relevant partial Views pages to GDS.
> Add tests for details on summary pages

- .nsprc
- app/views/apply/eligibility/claim/accommodation-details.html
- app/views/apply/eligibility/claim/car-hire-details.html
- app/views/apply/eligibility/claim/ferry-details.html
- app/views/apply/eligibility/claim/payment-details.html
- app/views/apply/eligibility/claim/plane-details.html
- app/views/apply/eligibility/claim/taxi-details.html
* remaining full page templates now in GDS (just partial views now remaining)
* remove old stray `.nsprc` file
> VB-367: Move remaining page templates to GDS

- app/views/apply/eligibility/claim/about-child.html
- app/views/apply/eligibility/claim/about-escort.html
- app/views/apply/eligibility/claim/bank-payment-details.html
- app/views/apply/eligibility/claim/bus-details.html
- app/views/apply/eligibility/claim/car-details.html
- app/views/apply/eligibility/claim/train-details.html
- app/views/apply/new-eligibility/about-the-prisoner.html
- app/views/apply/new-eligibility/about-you.html
- app/views/apply/new-eligibility/date-of-birth.html
- app/views/eligibility-fail.html
- app/views/start-already-registered.html
- test/cypress-e2e/integration/already-registerd-smoke-spec.js
- test/cypress-e2e/integration/first-time-advance-claim-ni-spec.js
- test/cypress-e2e/integration/first-time-advance-claim-ni-voucher-spec.js
- test/cypress-e2e/integration/first-time-advance-claim-spec.js
- test/cypress-e2e/integration/first-time-claim-ni-spec.js
- test/cypress-e2e/integration/first-time-claim-spec.js
- test/cypress-e2e/integration/repeat-claim-duplicate-spec.js
- test/cypress-e2e/integration/repeat-claim-new-contact-details-spec.js
- test/cypress-e2e/integration/repeat-new-eligibility-spec.js
- test/cypress-e2e/integration/update-claim-bank-details-spec.js
- test/cypress-e2e/integration/upload-later-send-message-spec.js
- test/cypress-e2e/integration/ycs-claim-spec.js
* Add `novalidate` to forms (GDS recommendation)
* Make use of Cypress selectors consistent
> VB-365: Code tidy

- app/routes/apply/new-eligibility/about-you.js
- app/views/ni-claimant.html
- test/unit/routes/apply/new-eligibility/test-about-you.js
Irritatingly had to do a fix for linting before this would run. Can do as a separate PR if preferred?
> VB-796: Don't allow NI based visitors to visit

- app/app.js
- app/azure-appinsights.js
- app/bin/www
- helm_deploy/help-with-prison-visits-external/values.yaml
Pretty sure data is coming through if my AppInsights check was correct.
> VB-1325: Update AppInsights connection string

- app/routes/your-claims/view-claim.js
Fix app crashing on unhandled promise rejection - see https://github.com/ministryofjustice/help-with-prison-visits-internal/pull/569 for details.
> VB-1287: Catch and throw unhandled promise rejections (GET /you-claims/:claimId)

- app/routes/apply/eligibility/claim/file-upload.js
- app/services/clam-av.js
- app/services/data/disable-non-ticketed-expenses-for-claim.js
- app/services/data/disable-old-claim-documents.js
- app/services/data/get-view-claim.js
- app/services/data/insert-repeat-duplicate-claim.js
- app/services/data/submit-claim.js
- app/services/data/submit-update.js
- app/services/data/visitor-prisoner-check.js
- package-lock.json
- package.json
All features that previously required the use of the `bluebird` module are natively available in nodejs.
> Remove bluebird module

- app/views/includes/layout.html
- app/views/technical-help.html
Update to the Help pages and associated links
> Hwpv 100 update help page and links

- app/views/technical-help.html
Noticed that the page title hadn't been updated - super small tweak.
> Updated page title on Help using the service page

- app/views/start-already-registered.html
- app/views/start.html
> HWPV-148: Remove upcoming maintenance message

- app/views/privacy.html
Updated privacy policy including:
* tidying language to match other services
* adding section on when it was last changed
* fixing Data Protection Officer email address
* removing reference to Post Office payment
> Updated privacy policy

- app/views/cookies.html
- app/views/includes/layout.html
Updated cookie page: https://dsdmoj.atlassian.net/browse/HWPV-160
> Update cookie page

- app/constants/prisons-enum.js
Matches new Scottish prisons in the async worker
> Added 3 new prisons and removed one old one #447

- app/assets/sass/application.scss
- app/views/your-claims/view-claim.html
Noticed banner was not rendering correctly - changed to mojBanner component
> Fixed poorly rendered banner with mojBanner

- app/assets/sass/application.scss
- app/views/your-claims/view-claim.html
Reverts ministryofjustice/help-with-prison-visits-external#887
> Revert "Fixed poorly rendered banner with mojBanner"

- helm_deploy/help-with-prison-visits-external/values.yaml
> Added productID

- app/constants/prisons-enum.js
> Added Millsike to prison list

- app/services/validators/validation-error-messages.js
- app/services/validators/validation-field-names.js
- app/views/apply/new-eligibility/about-the-prisoner.html
- app/views/partials/claim-summary/claim-summary-visit.html
- app/views/reference-recovery.html
- app/views/your-claims/check-your-information.html
- app/views/your-claims/your-claims.html
Updates public UI to include reference to "Prison number" in line with MOJ Design System recommendation. Also provides guidance on what this means.
> Update "prisoner number" to "prison number"

- app/views/apply/new-eligibility/benefits.html
Updated to provide notice that tax credits are being retired and removed from the service.
> Hwpv 234 update page with guidance on retirement of tax credits

- app/assets/sass/application.scss
- app/views/includes/layout.html
- app/views/your-claims/view-claim.html
Noticed some minor issues related to the content on the Summary page in the public service. This PR fixies those issues including:
* better Back link to match standard GDS approach
* improved Success banner
> Tweaks to the summary page

- app/views/reference-recovery.html
- app/views/start-already-registered.html
Tidied some of the wording related to the Returning booker and recovery journey.
> Text improvements to recovery pages

- app/views/apply/eligibility/claim/car-details.html
- app/views/apply/eligibility/claim/car-hire-details.html
- app/views/apply/eligibility/claim/light-refreshment-details.html
- app/views/partials/claim-summary/claim-summary-expenses.html
- test/cypress-e2e/integration/first-time-claim.cy.js
We need to change the mileages rate in SCOTLAND from 0.20 to 0.30.
The subsistence rate is also increased to £4.50 meal allowance over 5 hours.
Needs to be reviewed alongside https://github.com/ministryofjustice/help-with-prison-visits-asynchronous-worker/pull/465
> Hwpv 239 change rates for mileage and subsistence in scotland
