ministryofjustice/help-with-prison-visits-external

- app/routes/first-time/eligibility/claim/accommodation-details.js
- app/routes/first-time/eligibility/claim/bus-details.js
- app/routes/first-time/eligibility/claim/car-details.js
- app/routes/first-time/eligibility/claim/car-hire-details.js
- app/routes/first-time/eligibility/claim/expenses.js
- app/routes/first-time/eligibility/claim/ferry-details.js
- app/routes/first-time/eligibility/claim/light-refreshment-details.js
- app/routes/first-time/eligibility/claim/plane-details.js
- app/routes/first-time/eligibility/claim/taxi-details.js
- app/routes/first-time/eligibility/claim/train-details.js
- app/routes/first-time/eligibility/new-claim/journey-information.js
- app/routes/ux/claim/claim-details.js
- app/routes/ux/claim/claim-summary.js
- app/services/routing/expenses-url-router.js
- app/views/first-time/eligibility/claim/accommodation-details.html
- app/views/first-time/eligibility/claim/bus-details.html
- app/views/first-time/eligibility/claim/car-details.html
- app/views/first-time/eligibility/claim/car-hire-details.html
- app/views/first-time/eligibility/claim/ferry-details.html
- app/views/first-time/eligibility/claim/light-refreshment-details.html
- app/views/first-time/eligibility/claim/plane-details.html
- app/views/first-time/eligibility/claim/taxi-details.html
- app/views/first-time/eligibility/claim/train-details.html
- app/views/ux/claim/claim-details.html
- test/e2e/spec.js
This is a parital solution for #664.
**Url Router:**
- The leading param (i.e. the next page to redirect to) is now removed each time the Url Router is called such that we tend towards zero paramaters and thus redirect to claim-summary. 
- We now redirect to the origin url if the claimant selects add another journey.
- Now striping out trailing ampersands
- Prevent trailing question marks from being appended to the url.
**Routes:**
- The GET routes now pass the query params to the HTML page.
- Added the Url Validator to each of the GET routes.
**HTML:**
- The expense HTML pages now pass the params to the POST route so that they reach the next page in the chain.
**Tests:**
- Updated end-to-end test to extend to the claim-summary page. Includes calling three expense pages and selecting to …
> Feature/apvs 664/extend expense routing to route between expense pages

- package.json
- test/helpers/routes/route-helper.js
- test/unit/routes/first-time/eligibility/claim/ferry-details.js
- test/unit/routes/first-time/eligibility/claim/refreshment-details.js
- test/unit/routes/first-time/eligibility/claim/test-accommodation-details.js
- test/unit/routes/first-time/eligibility/claim/test-bus-details.js
- test/unit/routes/first-time/eligibility/claim/test-car-details.js
- test/unit/routes/first-time/eligibility/claim/test-hire-details.js
- test/unit/routes/first-time/eligibility/claim/test-plene-details.js
- test/unit/routes/first-time/eligibility/claim/test-taxi-details.js
- test/unit/routes/first-time/eligibility/claim/test-train-details.js
- test/unit/services/routing/test-expenses-url-router.js
- Added route tests for each of the expense pages.
- Added a route-helper that encapsulates the boiler plate route test setup.
- Added afterEach to package.json
> Added route tests for each of the expense pages.

- app/services/data/get-claim-summary.js
- app/views/first-time/eligibility/claim/claim-summary.html
- app/views/helpers/claim-expense-helper.js
- test/integration/services/data/test-get-claim-summary.js
- test/unit/views/helpers/test-claim-expense-helper.js
Updated the claim summary page.
- Now displays the name of each of the children the claimant entered.
- Indicates any child expenses with a the 'Child - ' prefix.
- Updated all relevant unit and integration tests.
> Feature/apvs 349/update claim summary to display child expenses and child details

- app/views/first-time/eligibility/new-claim/journey-information.html
The child selection on journey-information was not being repopulated on the form. Fixed this.
Closes #159.
> Fixed journey-information form repopulation on validation fail 

- app/constants/benefits-enum.js
- app/constants/helpers/enum-helper.js
- app/constants/prisoner-relationships-enum.js
- app/services/validators/common-validator.js
- test/unit/constants/helpers/test-enum-helper.js
- test/unit/services/domain/test-claim-summary.js
Added a generic enum helper.
- Moved the logic of the getByValue function from benefits to the helper.
- The function now checks that the type of the element it's dealing with is an object. I.e. it will ignore functions, arrays, nulls and undefined.
- The benefits enum wraps the call to the helper so the helper does not need to be explicitly added anywhere but in the enums.
- Added a unit test for the helper.
- Removed done calls from the test.
> Added a generic enum helper.

- app/routes/apply/new-eligibility/date-of-birth.js
- test/unit/routes/first-time/new-eligibility/test-date-of-birth.js
date-of-birth now handles non-validation errors. 
- Added unit test for else branch in the catch.
> date-of-birth now handles non-validation errors.

- test/unit/routes/test-eligibility-fail.js
Now uses the route helper.
No need for proxy require or sinon here as there is nothing to stub.
Works towards issue #125.
No need for proxy require or sinon here as there is nothing to stub.
> Eligibility Fail page now uses the route helper.

- test/helpers/routes/route-helper.js
- test/unit/routes/first-time/eligibility/claim/test-bank-account-details.js
test-bank-account-details route test now uses the route helper and sinon stubs.
Moved the cookie parser to the route helper.
Closes #125.
> Bank Account Details route test now uses the route helper and sinon stubs

- app/services/validators/common-validator.js
- test/unit/services/validators/test-common-validator.js
Fixed a bug that meant the expenses page validation would fail if only one option was selected.
- Was expecting the expenses to always be passed as an array, however if a single value is selected it is passed as a string.
- Modified the isValidExpenseArray function to handle this case.
- Added unit tests to cover this condition.
> Fixed expenses page validation bug

- app/assets/javascripts/moj.autocomplete.js
chore - fix prison name input styling
removed span wrapper which was effecting styling when there were errors
> chore - fix prison name input styling

- test/e2e/first-time-claim.js
Added click after setting autocomplete input value to ensure focus is cleared and allow the next click on the submit button to work on firefox
> chore - fix firefox e2e test

- test/helpers/routes/route-helper.js
- test/unit/routes/apply/eligibility/claim/test-about-child.js
- test/unit/routes/apply/eligibility/claim/test-about-escort.js
- test/unit/routes/apply/eligibility/claim/test-accommodation-details.js
- test/unit/routes/apply/eligibility/claim/test-bank-account-details.js
- test/unit/routes/apply/eligibility/claim/test-bus-details.js
- test/unit/routes/apply/eligibility/claim/test-car-details.js
- test/unit/routes/apply/eligibility/claim/test-car-hire-details.js
- test/unit/routes/apply/eligibility/claim/test-claim-summary.js
- test/unit/routes/apply/eligibility/claim/test-ferry-details.js
- test/unit/routes/apply/eligibility/claim/test-plane-details.js
- test/unit/routes/apply/eligibility/claim/test-refreshment-details.js
- test/unit/routes/apply/eligibility/claim/test-taxi-details.js
- test/unit/routes/apply/eligibility/claim/test-train-details.js
- test/unit/routes/apply/eligibility/new-claim/test-journey-information.js
- test/unit/routes/apply/eligibility/new-claim/test-same-journey-as-last-claim.js
- test/unit/routes/apply/new-eligibility/test-about-the-prisoner.js
- test/unit/routes/apply/new-eligibility/test-about-you.js
- test/unit/routes/test-feedback.js
- test/unit/routes/your-claims/test-check-your-information.js
- test/unit/routes/your-claims/test-update-contact-details.js
- test/unit/routes/your-claims/test-view-claim.js
- test/unit/routes/your-claims/test-your-claims.js
Updated the route helper to make this possible. 
Updated each of the routes that had an untested catch block. 
This brings a lot of our code coverage up to 100%.
Closes #144.
> Added unit tests to cover the .catch lines in each of the routes.

- app/services/data/get-claim-expense-by-id-or-last-approved.js
- app/services/data/get-last-claim-details.js
- app/services/data/insert-repeat-duplicate-claim.js
Modified get-claim-expenses-by-id-or-last-approved so that the Cost field will always be formatted as a string with 2 decimal places. 
Fixes error when inserting claim expenses for repeat duplicates.  Issue was caused because table function was returning Cost as an integer for whole numbers, and a string for numbers with decimal places.
> Fix conversion error when making repeat claim

- app/routes/apply/eligibility/claim/file-upload.js
- Also ensure that in this case the temp file is removed as this is usually
handled by the scan
> If the Clam AV child process fails for some reason, then handle the error

- app/routes/apply/eligibility/claim/file-upload.js
Fixed problems with post and upload later and problems with view claim uploads -> fixes e2e tests
* Moved addClaimIdIfNotBenefitDocument so it takes place for upload later and post later
* Added check for malware when coming from view claims page so upload later and post later will work
> Fixed upload later and post later with new malware checks

- app/routes/apply/eligibility/claim/file-upload.js
Copy file from temp directory to target location on Azure FS
Delete file from temp
> Azure FS does not work with fs.rename method

- app/services/domain/bank-account-details.js
- test/unit/services/domain/test-bank-account-details.js
chore - allow sort codes with hyphens
As per https://github.com/ministryofjustice/apvs-asynchronous-worker/issues/121
> chore - allow sort codes with hyphens

- app/routes/apply/new-eligibility/date-of-birth.js
- app/services/domain/date-of-birth.js
- test/unit/routes/apply/new-eligibility/test-date-of-birth.js
- test/unit/services/domain/test-date-of-birth.js
Modified DOB validation so that it returns an error message instead of redirecting to the eligibility-fail page.
Closes #370
> Age validation should now return error msg instead of redirect

- test/wdio.conf.sauce.ie8.jenkins.js
This test was reaching its timeout intermittently, which was a few minutes lower than the other tests.
> Increase ie8 e2e test timeout

- test/unit/services/domain/test-claim-summary.js
Added test to cover the case where a receipt is required and provided.
Split the VALID_IS_ADVANCE_CLAIM constant into two constants; IS_FUTURE_CLAIM and IS_PAST_CLAIM to make the tests intention more clear.
Improved test descriptions.
Brings test coverage up to 100%.
> Added/updated unit tests for test-claim-summary

- package.json
Have Istanbul (test coverage) ignore the data directory as we test via integration not unit tests.
> Have test coverage ignore the data directory

- test/unit/views/helpers/test-display-helper.js
Added unit tests for the getPrisonsByRegion function.
Stub the prisonsEnum and ensure the branch in which a non-object is present is exercised.
Brings test coverage up to 100%.
> Update unit tests for the display helper

- app/services/validators/field-validator.js
- app/services/validators/validation-error-messages.js
The getDropboxIsRequired message is not required as it simple copies the isRequired message. Removed it, and the code in the validator referring to it.
Brings code coverage up to 100%
> Removed the  getDropboxIsRequired message

- app/views/partials/claim-summary/claim-summary-events.html
- app/views/your-claims/view-claim.html
- Modified logic to show Rejected for advance claims with a status of rejected.
- Fixed issue where claim events don't always show in view-claim page.
See #401 for more info
> Fixed issue where claim events intermittently doesn't display

- app/constants/benefits-enum.js
- app/constants/helpers/enum-helper.js
- app/constants/helpers/prisons-helper.js
- app/constants/prisoner-relationships-enum.js
- app/routes/apply/new-eligibility/about-you.js
- app/routes/apply/new-eligibility/prisoner-relationship.js
- app/services/data/disable-non-ticketed-expenses-for-claim.js
- app/services/validators/common-validator.js
- app/views/apply/new-eligibility/prisoner-relationship.html
- app/views/helpers/display-helper.js
- test/unit/constants/helpers/test-enum-helper.js
- test/unit/routes/apply/new-eligibility/test-about-the-prisoner.js
- test/unit/routes/apply/new-eligibility/test-about-you.js
- test/unit/routes/apply/new-eligibility/test-benefits.js
- test/unit/routes/apply/new-eligibility/test-prisoner-relationship.js
- test/unit/services/domain/test-prisoner-relationship.js
- test/unit/services/validators/test-common-validator.js
- test/unit/services/validators/test-field-validator.js
- test/unit/services/validators/test-url-path-validator.js
Added to relationship enum to have a url value, also changed getKeyByValue to be getKeyByAttribute so it could be used for getting by urlValue as well. It defaults to most common usage of value if no attribute given.
* Added urlValue to prisoner relationships enum
* Changed getKeyByValue to getKeyByAttribute
* Updated html to have url values r1 - r7
* Updated routes, domains and validators to look for these values
> Feature/apvs 1062/add relationship url enum

- app/views/partials/claim-summary/claim-summary-expenses.html
- app/views/partials/claim-summary/claim-summary-visit.html
- app/views/partials/claim-summary/claim-summary-visitor.html
Since there is a back button and now old claim documents are removed if they exist when posting, change was still removing the document. Now it is just a link
> Changed change to be link rather than post to remove

- app/routes/apply/eligibility/claim/payment-details-and-declaration.js
- app/services/data/check-status-for-finishing-claim.js
- config.js
- test/integration/services/data/test-check-status-for-finishing-claim.js
- test/unit/routes/apply/eligibility/claim/test-payment-details-and-declaration.js
Add logic to handle double submission on the payment details page
* Added DB check of claim current status
* Added logic in route to assume claim already submitted to prevent double submission attempt
> Feature/apvs 1426/submitting twice when finishing claim

- test/integration/services/data/test-get-claim-summary.js
- test/integration/services/data/test-insert-new-claim.js
Due to DST the check for Date of Journey was failing on insert and claim summary - so changed to just check the date not the time
> Changed check from time based to date based

- app/routes/technical-help.js
- app/services/domain/technical-help.js
- app/services/validators/field-validator.js
- app/services/validators/fieldset-validator.js
- app/services/validators/validation-field-names.js
- app/views/technical-help.html
- test/unit/routes/test-technical-help.js
- test/unit/services/domain/test-technical-help.js
apvs-0050 addition of 2 extra help page fields, reference number and date of claim, and minor text changes. These additional fields are added to the Zendesk ticket. These fields are optional, so can be blank, but if any data is added to them, it is validated.
The format of the date added to Zendesk is done without using moment.format() as when it is used, the tests do not work, as POSTs to /help return a 500 error.
> Feature/apvs 0050/help new fields

- package-lock.json
- package.json
This temporarily removes artillery, we currently do not do any load testing and it has introduced even more alerts when bumping to the latest version.
> Bump dependencies 2021-11-05, remove artillery

- app/views/apply/new-eligibility/benefits.html
- test/cypress-e2e/integration/ycs-claim-spec.js
Nearly accidentally wiped out your YCS changes when moving to GDS so figured might be worth pausing to get this test in!
It runs part way through 'standard' flow to check YCS establishments & benefit **not** present. The, does a stripped-down assisted digital flow to check YCS options can be selected and claim submits OK.
> Add e2e test for YCS establishments & benefit

- app/app.js
Add 'www.google-analytics.com' to connect-src to fix Google Analytics browser console errors relating to Content Security Policy.
> Content Security Policy Fix for Google Analytics

- helm_deploy/help-with-prison-visits-external/values.yaml
Set `NODE_ENV` to `production` to stop error pages showing too much debug info.
> VB-1287: Set NODE_ENV to production

- package-lock.json
- package.json
Update for:
```bash
jsonwebtoken  <=8.5.1
Severity: high
jsonwebtoken has insecure input validation in jwt.verify function - https://github.com/advisories/GHSA-27h2-hvpr-p74q
jsonwebtoken's insecure implementation of key retrieval function could lead to Forgeable Public/Private Tokens from RSA to HMAC - https://github.com/advisories/GHSA-hjrf-2m68-5959
jsonwebtoken unrestricted key type could lead to legacy keys usage  - https://github.com/advisories/GHSA-8cf7-32gw-wr33
jsonwebtoken vulnerable to signature validation bypass due to insecure default algorithm in jwt.verify() - https://github.com/advisories/GHSA-qwph-4952-7xr6
```
> Update dependencies 2023-01-10

- app/views/apply/eligibility/claim/bank-payment-details.html
- app/views/apply/eligibility/claim/payout-confirmation.html
We have been informed that the date of removing the voucher payment has been finalised. Family Services are continuing with informing customers of the pending removal and have asked us to update the notification to say:
> Payment by cash voucher to end
>The payment by cash voucher option will no longer be available from 8 January 2024.
> Contact [familyservices.management@justice.gov.uk](mailto:familyservices.management@justice.gov.uk) for more information.
This needs to be updated on the following pages:
* Bank account details
* voucher confirmation
> Hwpv 125 update notification banner with new date for voucher withdrawal

- .circleci/config.yml
New IP allow lists weren't working for preprod because it was lacking the `hmpps-common-vars` context so couldn't get the IP groups.
> HWPV-124 Add common vars to preprod deployments

- app/constants/claim-event-enum.js
- test/unit/views/helpers/test-claim-event-helper.js
In the claims  history, we showed poorly rendered text when a contact had been updated for a claim.
This PR improves the wording by added an additional enum and updateing the relevant unit tests.
> Fixed poorly rendered text for when a contact has been updated
